#!/usr/bin/env bash

dawn_dir=$1
prefix=$dawn_dir/examples/python

examples=("copy_stencil" "hori_diff_stencil" "tridiagonal_solve_stencil" "unstructured_stencil" "global_index_stencil" "sparse_dimensions")

for ex in "${examples[@]}"; do
    python $prefix/${ex}.py
    if [ -r $prefix/data/${ex}_reference.cpp ]; then
        diff $prefix/data/${ex}.cpp $prefix/data/${ex}_reference.cpp
    fi
    rm $prefix/data/${ex}.cpp
done
