#!/usr/bin/env bash

source_dir=$1
build_dir=$2
install_dir=$3
build_jobs=24

# 1. Dawn
cmake -S $source_dir -B $build_dir \
    -DBUILD_TESTING=ON \
    -DCMAKE_INSTALL_PREFIX=$install_dir \
    ${@:4}

cmake --build $build_dir --parallel $build_jobs --target install

python -m pip install -e $source_dir/dawn

(cd $build_dir && ctest --output-on-failure --force-new-ctest-process)

# 2. Clang-GridTools
if [ -z ${CLANG_GRIDTOOLS_REPOSITORY+x} ]; then
  # ssh port is blocked on compute nodes, go via https port
  export CLANG_GRIDTOOLS_REPOSITORY=ssh://git@ssh.github.com:443/MeteoSwiss-APN/clang-gridtools.git
fi
if [ -z ${CLANG_GRIDTOOLS_BRANCH+x} ]; then
  export CLANG_GRIDTOOLS_BRANCH=master
fi

git clone --depth 1 -b $CLANG_GRIDTOOLS_BRANCH $CLANG_GRIDTOOLS_REPOSITORY

cmake -S clang-gridtools -B clang-gridtools/build \
    -DCMAKE_PREFIX_PATH=$install_dir \
    ${@:4}

cmake --build clang-gridtools/build --config $build_type --parallel $build_jobs

# Run tests
(cd clang-gridtools/build && ctest --output-on-failure --force-new-ctest-process)
