#!/usr/bin/env bash

set -e

run_tests=true
build_jobs=1

script_path=$(dirname $(which $0))
dawn_source_dir=$script_path/..
dawn_build_dir=$dawn_source_dir/build
dawn_install_dir=/usr/local

# Build arguments
build_args=()

while [ "$1" != "" ]; do
    case $1 in
    -j | --parallel)
        build_jobs=$2
        shift
        ;;
    -b | --dawn-build-dir)
        dawn_build_dir=$2
        shift
        ;;
    -c | --config)
        build_type=$2
        shift
        ;;
    --clang-gridtools-source-dir)
        cg_source_dir=$2
        shift
        ;;
    --clang-gridtools-build-dir)
        cg_build_dir=$2
        shift
        ;;
    -d | --dawn-source-dir)
        dawn_source_dir=$2
        shift
        ;;
    -n | --no-tests)
        run_tests=false
        ;;
    -i | --dawn-install-dir)
        dawn_install_dir=$2
        shift
        ;;
    *)
        build_args+=($1)
        ;;
    esac
    shift
done

# Dawn
cmake -S $dawn_source_dir -B $dawn_build_dir \
    -DBUILD_TESTING=ON \
    -DCMAKE_INSTALL_PREFIX=$dawn_install_dir \
    ${build_args[@]}

cmake --build $dawn_build_dir --config $build_type --parallel $build_jobs --target install

python -m pip install -e $dawn_source_dir/dawn

# Testing
if [ "$run_tests" == "true" ]; then
    (cd $dawn_build_dir && ctest --output-on-failure --force-new-ctest-process --quiet --max-width 80)

    # Clang-GridTools
    if [ -n "$cg_source_dir" ]; then
        if [ -n "$cg_build_dir" ]; then
            cg_build_dir=$cg_source_dir/build
        fi

        cmake -S $cg_source_dir -B $cg_build_dir \
            -DDawn_DIR=$dawn_install_dir/lib/cmake/Dawn \
            -DGTClang_DIR=$dawn_install_dir/lib/cmake/GTClang \
            ${build_args[@]}

        cmake --build $cg_build_dir --config $build_type --parallel $build_jobs

        (cd $cg_build_dir && ctest --output-on-failure --force-new-ctest-process --quiet --max-width 80)
    fi
fi
