#!/bin/bash
ignore_regex_list=(
    "^(\./)?dawn/test/utils/googletest/"
    "^(\./)?dawn/src/dawn/Support/External/"
    "^(\./)?dawn/examples/python/data/"
    "^(\./)?dawn/test/unit-test/test_dawn4py/data"
    "^(\./)?gtclang/test/utils/googletest/"
    "/bundle/"
    )
