var annotated_dup =
[
    [ "dawn", null, [
      [ "codegen", null, [
        [ "Class", "structdawn_1_1codegen_1_1Class.html", "structdawn_1_1codegen_1_1Class" ],
        [ "MemberFunction", "structdawn_1_1codegen_1_1MemberFunction.html", "structdawn_1_1codegen_1_1MemberFunction" ],
        [ "NewLine", "structdawn_1_1codegen_1_1NewLine.html", "structdawn_1_1codegen_1_1NewLine" ],
        [ "Statement", "structdawn_1_1codegen_1_1Statement.html", "structdawn_1_1codegen_1_1Statement" ],
        [ "Streamable", "classdawn_1_1codegen_1_1Streamable.html", "classdawn_1_1codegen_1_1Streamable" ],
        [ "Struct", "structdawn_1_1codegen_1_1Struct.html", "structdawn_1_1codegen_1_1Struct" ],
        [ "Structure", "structdawn_1_1codegen_1_1Structure.html", "structdawn_1_1codegen_1_1Structure" ],
        [ "Type", "structdawn_1_1codegen_1_1Type.html", "structdawn_1_1codegen_1_1Type" ],
        [ "Using", "structdawn_1_1codegen_1_1Using.html", "structdawn_1_1codegen_1_1Using" ]
      ] ],
      [ "sir", null, [
        [ "Attr", "classdawn_1_1sir_1_1Attr.html", "classdawn_1_1sir_1_1Attr" ],
        [ "Direction", "structdawn_1_1sir_1_1Direction.html", "structdawn_1_1sir_1_1Direction" ],
        [ "Field", "structdawn_1_1sir_1_1Field.html", "structdawn_1_1sir_1_1Field" ],
        [ "Interval", "structdawn_1_1sir_1_1Interval.html", "structdawn_1_1sir_1_1Interval" ],
        [ "Offset", "structdawn_1_1sir_1_1Offset.html", "structdawn_1_1sir_1_1Offset" ],
        [ "Stencil", "structdawn_1_1sir_1_1Stencil.html", "structdawn_1_1sir_1_1Stencil" ],
        [ "StencilCall", "structdawn_1_1sir_1_1StencilCall.html", "structdawn_1_1sir_1_1StencilCall" ],
        [ "StencilFunction", "structdawn_1_1sir_1_1StencilFunction.html", "structdawn_1_1sir_1_1StencilFunction" ],
        [ "StencilFunctionArg", "structdawn_1_1sir_1_1StencilFunctionArg.html", "structdawn_1_1sir_1_1StencilFunctionArg" ],
        [ "Value", "structdawn_1_1sir_1_1Value.html", "structdawn_1_1sir_1_1Value" ],
        [ "VerticalRegion", "structdawn_1_1sir_1_1VerticalRegion.html", "structdawn_1_1sir_1_1VerticalRegion" ]
      ] ],
      [ "Accesses", "classdawn_1_1Accesses.html", "classdawn_1_1Accesses" ],
      [ "add_const_past_pointer", "structdawn_1_1add__const__past__pointer.html", "structdawn_1_1add__const__past__pointer" ],
      [ "add_lvalue_reference_if_not_pointer", "structdawn_1_1add__lvalue__reference__if__not__pointer.html", "structdawn_1_1add__lvalue__reference__if__not__pointer" ],
      [ "AlignedCharArray", "structdawn_1_1AlignedCharArray.html", "structdawn_1_1AlignedCharArray" ],
      [ "AlignedCharArrayUnion", "structdawn_1_1AlignedCharArrayUnion.html", null ],
      [ "and_", "structdawn_1_1and__.html", null ],
      [ "and_< Cond, Conds... >", "structdawn_1_1and___3_01Cond_00_01Conds_8_8_8_01_4.html", null ],
      [ "ArrayRef", "classdawn_1_1ArrayRef.html", "classdawn_1_1ArrayRef" ],
      [ "AssignmentExpr", "classdawn_1_1AssignmentExpr.html", "classdawn_1_1AssignmentExpr" ],
      [ "AST", "classdawn_1_1AST.html", "classdawn_1_1AST" ],
      [ "ASTCodeGenCXX", "classdawn_1_1ASTCodeGenCXX.html", "classdawn_1_1ASTCodeGenCXX" ],
      [ "ASTCodeGenGTClangStencilBody", "classdawn_1_1ASTCodeGenGTClangStencilBody.html", "classdawn_1_1ASTCodeGenGTClangStencilBody" ],
      [ "ASTCodeGenGTClangStencilDesc", "classdawn_1_1ASTCodeGenGTClangStencilDesc.html", "classdawn_1_1ASTCodeGenGTClangStencilDesc" ],
      [ "ASTStringifer", "structdawn_1_1ASTStringifer.html", null ],
      [ "ASTVisitor", "classdawn_1_1ASTVisitor.html", "classdawn_1_1ASTVisitor" ],
      [ "ASTVisitorForwarding", "classdawn_1_1ASTVisitorForwarding.html", "classdawn_1_1ASTVisitorForwarding" ],
      [ "BinaryOperator", "classdawn_1_1BinaryOperator.html", "classdawn_1_1BinaryOperator" ],
      [ "BlockStmt", "classdawn_1_1BlockStmt.html", "classdawn_1_1BlockStmt" ],
      [ "BoundaryConditionDeclStmt", "classdawn_1_1BoundaryConditionDeclStmt.html", "classdawn_1_1BoundaryConditionDeclStmt" ],
      [ "Cache", "classdawn_1_1Cache.html", "classdawn_1_1Cache" ],
      [ "cast_convert_val", "structdawn_1_1cast__convert__val.html", null ],
      [ "cast_convert_val< To, FromTy, FromTy >", "structdawn_1_1cast__convert__val_3_01To_00_01FromTy_00_01FromTy_01_4.html", null ],
      [ "cast_retty", "structdawn_1_1cast__retty.html", "structdawn_1_1cast__retty" ],
      [ "cast_retty_impl", "structdawn_1_1cast__retty__impl.html", "structdawn_1_1cast__retty__impl" ],
      [ "cast_retty_impl< To, const From * >", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_5_01_4.html", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_5_01_4" ],
      [ "cast_retty_impl< To, const From *const  >", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_5const_01_01_4.html", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_5const_01_01_4" ],
      [ "cast_retty_impl< To, const From >", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_4.html", "structdawn_1_1cast__retty__impl_3_01To_00_01const_01From_01_4" ],
      [ "cast_retty_impl< To, From * >", "structdawn_1_1cast__retty__impl_3_01To_00_01From_01_5_01_4.html", "structdawn_1_1cast__retty__impl_3_01To_00_01From_01_5_01_4" ],
      [ "cast_retty_wrap", "structdawn_1_1cast__retty__wrap.html", "structdawn_1_1cast__retty__wrap" ],
      [ "cast_retty_wrap< To, FromTy, FromTy >", "structdawn_1_1cast__retty__wrap_3_01To_00_01FromTy_00_01FromTy_01_4.html", "structdawn_1_1cast__retty__wrap_3_01To_00_01FromTy_00_01FromTy_01_4" ],
      [ "CodeGen", "classdawn_1_1CodeGen.html", "classdawn_1_1CodeGen" ],
      [ "DawnCompiler", "classdawn_1_1DawnCompiler.html", "classdawn_1_1DawnCompiler" ],
      [ "DependencyGraph", "classdawn_1_1DependencyGraph.html", "classdawn_1_1DependencyGraph" ],
      [ "DependencyGraphAccesses", "classdawn_1_1DependencyGraphAccesses.html", "classdawn_1_1DependencyGraphAccesses" ],
      [ "DependencyGraphStage", "classdawn_1_1DependencyGraphStage.html", "classdawn_1_1DependencyGraphStage" ],
      [ "DiagnosticsBuilder", "classdawn_1_1DiagnosticsBuilder.html", "classdawn_1_1DiagnosticsBuilder" ],
      [ "DiagnosticsEngine", "classdawn_1_1DiagnosticsEngine.html", "classdawn_1_1DiagnosticsEngine" ],
      [ "DiagnosticsMessage", "classdawn_1_1DiagnosticsMessage.html", "classdawn_1_1DiagnosticsMessage" ],
      [ "DiagnosticsQueue", "classdawn_1_1DiagnosticsQueue.html", "classdawn_1_1DiagnosticsQueue" ],
      [ "DoMethod", "classdawn_1_1DoMethod.html", "classdawn_1_1DoMethod" ],
      [ "Expr", "classdawn_1_1Expr.html", "classdawn_1_1Expr" ],
      [ "ExprStmt", "classdawn_1_1ExprStmt.html", "classdawn_1_1ExprStmt" ],
      [ "Extent", "structdawn_1_1Extent.html", "structdawn_1_1Extent" ],
      [ "Extents", "classdawn_1_1Extents.html", "classdawn_1_1Extents" ],
      [ "Field", "structdawn_1_1Field.html", "structdawn_1_1Field" ],
      [ "FieldAccessExpr", "classdawn_1_1FieldAccessExpr.html", "classdawn_1_1FieldAccessExpr" ],
      [ "FunCallExpr", "classdawn_1_1FunCallExpr.html", "classdawn_1_1FunCallExpr" ],
      [ "function_ref", "classdawn_1_1function__ref.html", null ],
      [ "function_ref< Ret(Params...)>", "classdawn_1_1function__ref_3_01Ret_07Params_8_8_8_08_4.html", "classdawn_1_1function__ref_3_01Ret_07Params_8_8_8_08_4" ],
      [ "GTClangCodeGen", "classdawn_1_1GTClangCodeGen.html", "classdawn_1_1GTClangCodeGen" ],
      [ "GTClangNaiveCXXCodeGen", "classdawn_1_1GTClangNaiveCXXCodeGen.html", "classdawn_1_1GTClangNaiveCXXCodeGen" ],
      [ "HardwareConfig", "structdawn_1_1HardwareConfig.html", "structdawn_1_1HardwareConfig" ],
      [ "IfStmt", "classdawn_1_1IfStmt.html", "classdawn_1_1IfStmt" ],
      [ "Interval", "classdawn_1_1Interval.html", "classdawn_1_1Interval" ],
      [ "is_callable", "structdawn_1_1is__callable.html", null ],
      [ "is_simple_type", "structdawn_1_1is__simple__type.html", null ],
      [ "isa_impl", "structdawn_1_1isa__impl.html", null ],
      [ "isa_impl_cl", "structdawn_1_1isa__impl__cl.html", null ],
      [ "isa_impl_cl< To, const From * >", "structdawn_1_1isa__impl__cl_3_01To_00_01const_01From_01_5_01_4.html", null ],
      [ "isa_impl_cl< To, const From *const  >", "structdawn_1_1isa__impl__cl_3_01To_00_01const_01From_01_5const_01_01_4.html", null ],
      [ "isa_impl_cl< To, const From >", "structdawn_1_1isa__impl__cl_3_01To_00_01const_01From_01_4.html", null ],
      [ "isa_impl_cl< To, From * >", "structdawn_1_1isa__impl__cl_3_01To_00_01From_01_5_01_4.html", null ],
      [ "isa_impl_cl< To, From *const  >", "structdawn_1_1isa__impl__cl_3_01To_00_01From_01_5const_01_01_4.html", null ],
      [ "isa_impl_wrap", "structdawn_1_1isa__impl__wrap.html", null ],
      [ "isa_impl_wrap< To, FromTy, FromTy >", "structdawn_1_1isa__impl__wrap_3_01To_00_01FromTy_00_01FromTy_01_4.html", null ],
      [ "isPodLike", "structdawn_1_1isPodLike.html", null ],
      [ "isPodLike< StringRef >", "structdawn_1_1isPodLike_3_01StringRef_01_4.html", null ],
      [ "LiteralAccessExpr", "classdawn_1_1LiteralAccessExpr.html", "classdawn_1_1LiteralAccessExpr" ],
      [ "Logger", "classdawn_1_1Logger.html", "classdawn_1_1Logger" ],
      [ "LoggerInterface", "classdawn_1_1LoggerInterface.html", "classdawn_1_1LoggerInterface" ],
      [ "MakeIndent", "structdawn_1_1MakeIndent.html", null ],
      [ "MakeIndent< 0 >", "structdawn_1_1MakeIndent_3_010_01_4.html", null ],
      [ "MakeIndent< 1 >", "structdawn_1_1MakeIndent_3_011_01_4.html", null ],
      [ "MakeIndent< 2 >", "structdawn_1_1MakeIndent_3_012_01_4.html", null ],
      [ "MakeIndent< 3 >", "structdawn_1_1MakeIndent_3_013_01_4.html", null ],
      [ "MakeIndent< 4 >", "structdawn_1_1MakeIndent_3_014_01_4.html", null ],
      [ "MultiStage", "classdawn_1_1MultiStage.html", "classdawn_1_1MultiStage" ],
      [ "MutableArrayRef", "classdawn_1_1MutableArrayRef.html", "classdawn_1_1MutableArrayRef" ],
      [ "NonCopyable", "classdawn_1_1NonCopyable.html", "classdawn_1_1NonCopyable" ],
      [ "OptimizerContext", "classdawn_1_1OptimizerContext.html", "classdawn_1_1OptimizerContext" ],
      [ "Options", "structdawn_1_1Options.html", null ],
      [ "OwningArrayRef", "classdawn_1_1OwningArrayRef.html", "classdawn_1_1OwningArrayRef" ],
      [ "Pass", "classdawn_1_1Pass.html", "classdawn_1_1Pass" ],
      [ "PassDataLocalityMetric", "classdawn_1_1PassDataLocalityMetric.html", "classdawn_1_1PassDataLocalityMetric" ],
      [ "PassFieldVersioning", "classdawn_1_1PassFieldVersioning.html", "classdawn_1_1PassFieldVersioning" ],
      [ "PassInlining", "classdawn_1_1PassInlining.html", "classdawn_1_1PassInlining" ],
      [ "PassManager", "classdawn_1_1PassManager.html", "classdawn_1_1PassManager" ],
      [ "PassMultiStageSplitter", "classdawn_1_1PassMultiStageSplitter.html", "classdawn_1_1PassMultiStageSplitter" ],
      [ "PassPrintStencilGraph", "classdawn_1_1PassPrintStencilGraph.html", "classdawn_1_1PassPrintStencilGraph" ],
      [ "PassSetCaches", "classdawn_1_1PassSetCaches.html", "classdawn_1_1PassSetCaches" ],
      [ "PassSetStageGraph", "classdawn_1_1PassSetStageGraph.html", "classdawn_1_1PassSetStageGraph" ],
      [ "PassSetStageName", "classdawn_1_1PassSetStageName.html", "classdawn_1_1PassSetStageName" ],
      [ "PassSSA", "classdawn_1_1PassSSA.html", "classdawn_1_1PassSSA" ],
      [ "PassStageMerger", "classdawn_1_1PassStageMerger.html", "classdawn_1_1PassStageMerger" ],
      [ "PassStageReordering", "classdawn_1_1PassStageReordering.html", "classdawn_1_1PassStageReordering" ],
      [ "PassStageSplitter", "classdawn_1_1PassStageSplitter.html", "classdawn_1_1PassStageSplitter" ],
      [ "PassStencilSplitter", "classdawn_1_1PassStencilSplitter.html", "classdawn_1_1PassStencilSplitter" ],
      [ "PassTemporaryFirstAccess", "classdawn_1_1PassTemporaryFirstAccess.html", "classdawn_1_1PassTemporaryFirstAccess" ],
      [ "PassTemporaryMerger", "classdawn_1_1PassTemporaryMerger.html", "classdawn_1_1PassTemporaryMerger" ],
      [ "PassTemporaryType", "classdawn_1_1PassTemporaryType.html", "classdawn_1_1PassTemporaryType" ],
      [ "RangeToString", "classdawn_1_1RangeToString.html", "classdawn_1_1RangeToString" ],
      [ "ReadBeforeWriteConflict", "structdawn_1_1ReadBeforeWriteConflict.html", "structdawn_1_1ReadBeforeWriteConflict" ],
      [ "ReoderStrategyGreedy", "classdawn_1_1ReoderStrategyGreedy.html", "classdawn_1_1ReoderStrategyGreedy" ],
      [ "ReoderStrategyPartitioning", "classdawn_1_1ReoderStrategyPartitioning.html", "classdawn_1_1ReoderStrategyPartitioning" ],
      [ "ReorderStrategy", "classdawn_1_1ReorderStrategy.html", "classdawn_1_1ReorderStrategy" ],
      [ "ReturnStmt", "classdawn_1_1ReturnStmt.html", "classdawn_1_1ReturnStmt" ],
      [ "simplify_type", "structdawn_1_1simplify__type.html", "structdawn_1_1simplify__type" ],
      [ "simplify_type< const From >", "structdawn_1_1simplify__type_3_01const_01From_01_4.html", "structdawn_1_1simplify__type_3_01const_01From_01_4" ],
      [ "SIR", "structdawn_1_1SIR.html", "structdawn_1_1SIR" ],
      [ "SIRSerializerJSON", "classdawn_1_1SIRSerializerJSON.html", null ],
      [ "SmallString", "classdawn_1_1SmallString.html", "classdawn_1_1SmallString" ],
      [ "SmallVector", "classdawn_1_1SmallVector.html", "classdawn_1_1SmallVector" ],
      [ "SmallVectorBase", "classdawn_1_1SmallVectorBase.html", "classdawn_1_1SmallVectorBase" ],
      [ "SmallVectorImpl", "classdawn_1_1SmallVectorImpl.html", "classdawn_1_1SmallVectorImpl" ],
      [ "SmallVectorStorage", "structdawn_1_1SmallVectorStorage.html", "structdawn_1_1SmallVectorStorage" ],
      [ "SmallVectorStorage< T, 0 >", "structdawn_1_1SmallVectorStorage_3_01T_00_010_01_4.html", null ],
      [ "SmallVectorStorage< T, 1 >", "structdawn_1_1SmallVectorStorage_3_01T_00_011_01_4.html", null ],
      [ "SmallVectorTemplateBase", "classdawn_1_1SmallVectorTemplateBase.html", "classdawn_1_1SmallVectorTemplateBase" ],
      [ "SmallVectorTemplateBase< T, true >", "classdawn_1_1SmallVectorTemplateBase_3_01T_00_01true_01_4.html", "classdawn_1_1SmallVectorTemplateBase_3_01T_00_01true_01_4" ],
      [ "SmallVectorTemplateCommon", "classdawn_1_1SmallVectorTemplateCommon.html", "classdawn_1_1SmallVectorTemplateCommon" ],
      [ "SourceLocation", "structdawn_1_1SourceLocation.html", "structdawn_1_1SourceLocation" ],
      [ "Stage", "classdawn_1_1Stage.html", "classdawn_1_1Stage" ],
      [ "Statement", "structdawn_1_1Statement.html", "structdawn_1_1Statement" ],
      [ "StatementAccessesPair", "classdawn_1_1StatementAccessesPair.html", "classdawn_1_1StatementAccessesPair" ],
      [ "Stencil", "classdawn_1_1Stencil.html", "classdawn_1_1Stencil" ],
      [ "StencilCallDeclStmt", "classdawn_1_1StencilCallDeclStmt.html", "classdawn_1_1StencilCallDeclStmt" ],
      [ "StencilFunArgExpr", "classdawn_1_1StencilFunArgExpr.html", "classdawn_1_1StencilFunArgExpr" ],
      [ "StencilFunCallExpr", "classdawn_1_1StencilFunCallExpr.html", "classdawn_1_1StencilFunCallExpr" ],
      [ "StencilFunctionInstantiation", "classdawn_1_1StencilFunctionInstantiation.html", "classdawn_1_1StencilFunctionInstantiation" ],
      [ "StencilInstantiation", "classdawn_1_1StencilInstantiation.html", "classdawn_1_1StencilInstantiation" ],
      [ "Stmt", "classdawn_1_1Stmt.html", "classdawn_1_1Stmt" ],
      [ "StringRef", "classdawn_1_1StringRef.html", "classdawn_1_1StringRef" ],
      [ "StringSwitch", "classdawn_1_1StringSwitch.html", "classdawn_1_1StringSwitch" ],
      [ "TernaryOperator", "classdawn_1_1TernaryOperator.html", "classdawn_1_1TernaryOperator" ],
      [ "TranslationUnit", "classdawn_1_1TranslationUnit.html", "classdawn_1_1TranslationUnit" ],
      [ "Twine", "classdawn_1_1Twine.html", "classdawn_1_1Twine" ],
      [ "Type", "classdawn_1_1Type.html", "classdawn_1_1Type" ],
      [ "UIDGenerator", "classdawn_1_1UIDGenerator.html", "classdawn_1_1UIDGenerator" ],
      [ "UnaryOperator", "classdawn_1_1UnaryOperator.html", "classdawn_1_1UnaryOperator" ],
      [ "UnittestLogger", "classdawn_1_1UnittestLogger.html", "classdawn_1_1UnittestLogger" ],
      [ "VarAccessExpr", "classdawn_1_1VarAccessExpr.html", "classdawn_1_1VarAccessExpr" ],
      [ "VarDeclStmt", "classdawn_1_1VarDeclStmt.html", "classdawn_1_1VarDeclStmt" ],
      [ "VerticalRegionDeclStmt", "classdawn_1_1VerticalRegionDeclStmt.html", "classdawn_1_1VerticalRegionDeclStmt" ]
    ] ]
];