name: 'Master into OffsetReduction'

on:
  push:
    branches:
    - master

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: dawn-ico/gh-action-nightly-merge@master
      with:
        stable_branch: 'master'
        development_branch: 'offsetReduction'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
